### ISSUE TITLE
Join Channels

### ISSUE THREAD

**Issue by graywolf336** [kenjij/lita-slack#13]
How does one get the bot to join other channels? Right now it is only in general and I'd like it in a few other channels. I tried `lita join #random` but the console outputted `[2015-01-20 01:57:18 UTC] WARN: This adapter has not implemented #join.` which I assume means it currently isn't implemented?

**Comment by jimmycuadra** [comment]
You can just invite it to a channel/group via the Slack UI as you would any other user and it should join automatically.

**Comment by graywolf336** [comment]
Ah, thanks that worked. :+1:
