### ISSUE TITLE
FR: Reconnect when the link is disconnected.

### ISSUE THREAD

**Issue by ikeji** [kenjij/lita-slack#15]
Today, my bot was not respond to chat.
I checked the log and I found this line.
```
INFO: Disconnected from Slack.
```
I guess the lita-slack does not reconnect when the connection is lost.
Is there any way to reconnect to slack server?

**Comment by josqu4red** [comment]
Had the case a few times on my instance, just after a ```team_migration_started``` event.

**Comment by josacar** [comment]
Maybe the simplest thing is shutdown the robot like this:

```ruby
websocket.on(:close) { log.info("Disconnected from Slack."); robot.shut_down }
```

**Comment by jimmycuadra** [comment]
Agreed. Reconnection should be handled by a process manager. What lita-slack should do is make sure the process shuts down correctly when the connection is lost.

**Comment by ikeji** [comment]
Thanks a lot!!

**Comment by jimmycuadra** [comment]
You're welcome! This was released in gem version 1.1.0.

**Comment by josacar** [comment]
Thanks!

**Comment by reidblomquist** [comment]
@jimmycuadra why is it your opinion that this should be handled by a process manager instead of making this process bulletproof? as far as I know the IRC adapter can auto reconnect...

**Comment by jimmycuadra** [comment]
If someone wants to implement auto-reconnection, I'd be happy to take a PR. See litaio/lita-hipchat#20 for a discussion on this topic in the HipChat adapter where people convinced me the plugin should do it.

**Comment by reidblomquist** [comment]
Awesome, thanks for the input @jimmycuadra - will read over your comments there and work on putting together a PR.
