### ISSUE TITLE
DNS resolution fails

### ISSUE THREAD

**Issue by geefinator** [kenjij/lita-slack#37]
Hello,

I am trying to set up our lita bot and any time I am using the Slack adapter DNS resolution fails.  This obviously makes writing plugins for my environment near impossible.  The same DNS calls in the Shell adapter work perfectly.  You can re-create this by just firing up a lita instance connected to slack and do any sort of operation that would require a dns resolution to complete.  Easiest way to test is is install lita-dig and use that.  It will fail every time if it's connected to the slack adapter, at least it has for me :(

**Comment by jimmycuadra** [comment]
Sorry you're having trouble with this. How is your bot deployed? Have you tried it with another adapter like IRC or HipChat?

**Comment by geefinator** [comment]
Hey there @jimmycuadra .  The bot is deployed on an Ubuntu 14.04 server running ruby 2.1.2.

I just went ahead and set it up with Hipchat and all DNS resolution works correctly.  So far the only adapter that has an issue is the slack adapter.

**Comment by geefinator** [comment]
Pretty sure I figured out why this is happening, but I am not sure how to fix it.  Slack seems to transform hostname strings into a rich url with the following format:

<http://thehostname.you.typed|thehostname.you.typed>

Which is exactly what comes back within response.matches within the handler routing.  So, most plugins assume this will be just a plain string, however it is not and therefore fails with the proper error of not being able to resolve, cause it actually can't resolve that.  Like i said not sure if that's fixable or not within the adapter.  I would assume not since it is default slack behavior...I can dev my plugins to be aware of this, but it'd be awesome if it could be fixed somewhere further up the stack :)

**Comment by geefinator** [comment]
Verified that this is what's happening in my other plugin that was having this same issue.  My fix is to strip response.matches like so:

`response.matches[0][0].split('|')[1].gsub(/>$/,'')`

which gets rid of the weird formatting leaving just the hostname.

**Comment by jimmycuadra** [comment]
Ah, yes. Slack's message formatting has been a big problem for chat bots. #35 is in progress to address this, so you may want to follow that. I'm gonna close this one and just keep tracking the issue there.
