### ISSUE TITLE
Cannot send message on connected event

### ISSUE THREAD

**Issue by epinault** [kenjij/lita-slack#39]
I am using the lastest version of lita slack 1.4.0 and the following code does not work in my handler. Works fine with a shell adapter.. Nothing crashes. I see the send_messages call into the send_messages of the slack adapter . Then the Event.defer. but nothing every come to slack (maybe an issue with websocket?) 

```
module Lita
  module Handlers
    class MyHandler < Handler
    on :connected, :lunch_notifier
	  
   def lunch_notifier(payload)
        p :lunch_notifier
        target = Source.new(room: '#general')
        robot.send_messages(target, ['test'])
  end
end
end
```

**Comment by epinault** [comment]
So I found the problem.. The source room is not of type #general but instead an ID! Once I specify the ID instead of the room name, then it all works.. Seems like there is a mapping issue somewhere

**Comment by freibuis** [comment]
this might have to do with the slack formatting issue. I have tested it on my dev branch and its ok.  Look at #35. I should have all the test completed tomorrow when I have some time.

**Comment by jimmycuadra** [comment]
This is effectively a limitation of Lita, since it has no concept of a room as a first class citizen like how users are treated. In other words, there is no mapping of user-facing room name to room ID stored anywhere like there is for users. I plan to address it in Lita in the future.

**Comment by freibuis** [comment]
@jimmycuadra   I have added channel mapping support here https://github.com/freibuis/lita-slack/tree/channel_mapping

This works in debugger no problem but my but my tests for it and it breaks.
```
- #<Lita::Adapters::Slack::ChannelMapping:0x0000000370eb78
  @mapping={"C2147483705"=>"general"}>]
+ #<Lita::Adapters::Slack::ChannelMapping:0x0000000370b950
  @mapping={"C2147483705"=>"general"}>]
```
once I the tests for channel_mapping complete I will merge it with my url_un_formatting branch

**Comment by jimmycuadra** [comment]
Cool, I'm interested to see your approach for handling this without support for rooms as first class citizens in Lita core.

I'd keep this branch separate from your other PR so they can be addressed and/or merged separately, since they're not related.

**Comment by freibuis** [comment]
The formatting code requires to know about rooms.. so it needs to be their. other wise I will be able  o format channels/rooms as hubot-slack has done.

**Comment by jimmycuadra** [comment]
A better solution for this is now possible in the just-released lita-slack 1.5. You can do this:

```
Source.new(room: Lita::Room.find_by_name('general'))
```

Then you don't have to find the channel ID on your own.

**Comment by epinault** [comment]
Oh! I ll check it out then. thanks!

**Comment by justin999** [comment]
@jimmycuadra you saved my life. I was able to set target by 
```
Source.new(room: Lita::Room.find_by_name('general'))
```
