### ISSUE TITLE
How to get channel ids

### ISSUE THREAD

**Issue by crunis** [kenjij/lita-slack#40]
In some occasions I want to send a message in a different room from the one that robot was called. What is the proper way to translate the channel/room name into a channel id ? 

I know one option would be to make an API request and retrieve the full list of channels, but is there another way?

And then, to DM users, how can I get the corresponding channel id to DM them ? 

So far I've just created a `lita say channel` command that gets the channel id from "response.message.source.room", and then store it in a table for later use. Is there a more direct way?

Thanks

**Comment by jimmycuadra** [comment]
There isn't a better way to do it right now, but the next version of Lita will treat channels as first-class citizens like users, and will include a "rooms find" command that works like the "users find" command. The latter command can be used today to find the Slack Direct Message ID for that user.

**Comment by crunis** [comment]
Right, I've just found the "User.find_XXXX" methods some minutes ago.
I'll wait for the next version of Lita, then!

Thank you !

**Comment by spkane** [comment]
Did the ```rooms find``` functionality ever get added? It does not seem to exist in the current stable release?

**Comment by jimmycuadra** [comment]
No, it doesn't look like "rooms find" has been implemented yet.
