### ISSUE TITLE
Is there any way to get proper debug report about problem?

### ISSUE THREAD

**Issue by aruzmeister** [kenjij/lita-slack#48]
When i try to run some of command the only thing i get is...
```
[2015-07-30 18:11:04 UTC] INFO: Connected to Slack.
[2015-07-30 18:11:12 UTC] INFO: Disconnected from Slack.
```

**Comment by jimmycuadra** [comment]
You can get a little bit more information by setting the logging level to debug. In your lita_config.rb file:

``` ruby
config.robot.log_level = :debug
```

If this isn't enough to help figure out whatever problem is happening, I'd definitely accept a PR adding more debug logging.
