### ISSUE TITLE
Ability to ignore single channel guests and restricted users

### ISSUE THREAD

**Issue by adamgibbins** [kenjij/lita-slack#54]
We're a pretty open company, thus do not whitelist Lita commands to various users - everyone can do everything.  We do however open our #random channel to company alumni and other "friends of the company", we add them as single channel guests.  Currently Slack doesn't allow any way to restrict direct messages - meaning any of these members can query Lita.

We don't want this is, it'd be ideal if we could disable access to Lita for users with the "is_ultra_restricted" or "is_restricted" flags on the global level.

**Comment by jimmycuadra** [comment]
This would be possible with an extension. Use the `validate_route` hook to prevent routes from matching based on any arbitrary criteria you like. http://docs.lita.io/plugin-authoring/extensions/

**Comment by adamgibbins** [comment]
Great, thank you - apologies for the ignorant question.

**Comment by jimmycuadra** [comment]
Not a problem! There a lot of intricate details in Lita and it can be hard to discover and learn them all.
