### ISSUE TITLE
Error during start up in user create in 1.7.1

### ISSUE THREAD

**Issue by manicholls** [kenjij/lita-slack#57]
I'm seeing a problem, that I believe, is while the bot is creating users in Redis using 1.7.1.  I'm not seeing this in 1.7.0 so I think it has to do with parsing the metadata for a particular user but I'm not able to determine what data is causing the error.

Here's the full debug output of the startup error, which I'm afraid won't be very useful.

/var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:129:in `value': ERR wrong number of arguments for HMSET (Redis::CommandError)
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:121:in `_set'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:67:in `block in finish'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:66:in `each'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:66:in `each_with_index'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:66:in `each'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:66:in `map'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/pipeline.rb:66:in `finish'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:149:in `block in call_pipeline'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:147:in `call_pipeline'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:2136:in `block in pipelined'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /var/lib/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:2132:in `pipelined'
	from /var/lib/gems/2.1.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:414:in `namespaced_block'
	from /var/lib/gems/2.1.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:266:in `pipelined'
	from /var/lib/gems/2.1.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:414:in `namespaced_block'
	from /var/lib/gems/2.1.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:266:in `pipelined'
	from /var/lib/gems/2.1.0/gems/lita-4.6.1/lib/lita/user.rb:109:in `save'
	from /var/lib/gems/2.1.0/gems/lita-4.6.1/lib/lita/user.rb:22:in `create'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/user_creator.rb:9:in `create_user'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/user_creator.rb:22:in `block in create_users'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/user_creator.rb:22:in `each'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/user_creator.rb:22:in `create_users'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/rtm_connection.rb:31:in `initialize'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/rtm_connection.rb:20:in `new'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack/rtm_connection.rb:20:in `build'
	from /var/lib/gems/2.1.0/gems/lita-slack-1.7.1/lib/lita/adapters/slack.rb:22:in `run'
	from /var/lib/gems/2.1.0/gems/lita-4.6.1/lib/lita/robot.rb:80:in `run'
	from /var/lib/gems/2.1.0/gems/lita-4.6.1/lib/lita.rb:80:in `run'
	from /var/lib/gems/2.1.0/gems/lita-4.6.1/lib/lita/cli.rb:77:in `start'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/lita-4.6.1/bin/lita:6:in `<top (required)>'
	from /usr/local/bin/lita:23:in `load'
	from /usr/local/bin/lita:23:in `<main>'

If there is anything further I can provide to help, please let me know.

**Comment by lhagemann** [comment]
++ seeing same error; solved by pinning to 1.7.0

**Comment by jimmycuadra** [comment]
cc @byroot

**Comment by byroot** [comment]
That is weird, we have no such issue, we're not running 1.7.1 though, but a patched 1.7.0: https://github.com/Shopify/lita-slack/commit/21113ff5861c

I'll see what I can do.

**Comment by byroot** [comment]
Ok, good news, I'm able to repro. I'll try to get a fix tonight.

**Comment by WarhammerMarine** [comment]
+1 I am seeing the same issue, reverted back to 1.7.0

**Comment by manicholls** [comment]
Thanks everyone for the quick responses

**Comment by Ginja** [comment]
+1

**Comment by jimmycuadra** [comment]
Reverted the offending code. You can update to gem version 1.7.2, which is the same as 1.7.0.

**Comment by istensky** [comment]
But now the version of 1.7.2 does not records email

**Comment by byroot** [comment]
@istensky this will do:

```ruby
class UserEmail < Lita::Handler
  on :slack_user_created, :store_email

  def store_email(slack_user: )
    profile = slack_user.metadata['profile']
    email = profile && profile['email'].presence
    return unless email

    lita_user = Lita::User.find_by_id(slack_user.id)
    return unless lita_user

    lita_user.metadata['email'] = email
    lita_user.save
  end
end

Lita.register_handler(UserEmail)
```
