### ISSUE TITLE
lita gets disconnected almost immediately

### ISSUE THREAD

**Issue by miketheman** [kenjij/lita-slack#66]
Stacktrace:

```
[2015-12-09 23:39:32 UTC] INFO: Disconnected from Slack.
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder': undefined method `encode' for ActiveSupport::JSON:Module (NoMethodError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
    from /usr/local/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
    from /usr/local/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
    from /usr/local/lib/ruby/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/rtm_connection.rb:89:in `payload_for'
    from /usr/local/lib/ruby/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/rtm_connection.rb:104:in `safe_payload_for'
    from /usr/local/lib/ruby/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/rtm_connection.rb:62:in `block (2 levels) in send_messages'
    from /usr/local/lib/ruby/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
    from /usr/local/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'
```

This is in a container built from `litaio/ruby:latest`, and:

    activesupport (4.2.5)
    eventmachine (1.0.8)
    json (1.8.3)
    multi_json (1.11.2)

Happy to provide any other debugging info.

**Comment by miketheman** [comment]
note: I actually think this is not this gem's responsibility to handle json gem interaction - I'm getting activesupport (and thereby json) via lita-pagerduty and its deps - so I'm going to remove it for now from my deployment.

**Comment by jimmycuadra** [comment]
Thanks for the report. I think you're correct that this has to do with a bad interaction between two other gems. Since Active Support is not a dependency of lita or lita-slack, I think it's out of scope for either project to attempt to address this. If you want to add it back to your code, you can probably work around it by manually configuring MultiJson to use a different JSON library.
