### ISSUE TITLE
Can't provide user as target for send_messages

### ISSUE THREAD

**Issue by liamdawson** [kenjij/lita-slack#70]
robot.send_message(user, "This should be a private message.")

fails, where `user` is `response.user`.

According to the Lita API, this should work: http://www.rubydoc.info/gems/lita/Lita/Robot#send_messages-instance_method

The error it fails with is:

    ERROR:  crashed. The exception was:
    undefined method `private_message?' for #<Lita::User:0x00562d8bf1abd0>
    Full backtrace:
    /usr/local/bundle/gems/lita-slack-1.7.2/lib/lita/adapters/slack.rb:50:in `channel_for'
    /usr/local/bundle/gems/lita-slack-1.7.2/lib/lita/adapters/slack.rb:29:in `send_messages'
    /usr/local/bundle/gems/lita-4.6.1/lib/lita/robot.rb:129:in `send_messages'

I tried to work around it by using `Room.find_by_id(user.id)` instead, but I received the same error.

**Comment by liamdawson** [comment]
I'm using the following workaround for now:

    target = OpenStruct.new('private_message?': true, user: user)
          robot.send_message(target, "Here's a private message.")

If no-one else has gotten around to it when I've finished this, I'll try contributing the fix.

**Comment by jimmycuadra** [comment]
The first argument to `Robot#send_messages` is a `Lita::Source` object. Just wrap the User in a Source and pass the Source in and it will work.

http://www.rubydoc.info/gems/lita/Lita/Robot#send_messages-instance_method

**Comment by liamdawson** [comment]
Thanks, I'm surprised this isn't a little clearer in the Lita docs.

**Comment by jimmycuadra** [comment]
I'd happily accept a PR to https://github.com/litaio/docs.lita.io to make it more clear. Especially if there was a particular section or phrase that mislead you.
