### ISSUE TITLE
Feature Request: Undo Effects of Slack's URL Autolinking Before Passing Input Downstream?

### ISSUE THREAD

**Issue by consultantRR** [kenjij/lita-slack#9]
Hello,

I have previously conversed a little with the support team at Slack about this issue, @paulhammond included.

Essentially, the issue is that Slack rewrites domain names and FQHNs as clickable URLs, essentially rewriting a user's input of "apple.com" to (I believe) `<http://apple.com|apple.com>`, which is obviously handy most of the time within Slack, but in regards to Lita, it breaks several plugins. Two examples are `lita-whois` and `lita-dig`.

Paul indicated that the hubot adapter recently addressed this (https://github.com/slackhq/hubot-slack/issues/109), and that he would be amenable to chiming in here in regards to a discussion on how best to approach this in `lita-slack`.

**Comment by freibuis** [comment]
I have created a pull request #35 that only effects url formatting. its a horrible hack. slack-rtm api should have an option on connection to say. "hay I'm simple please don't format for me" but it looks like the message is formatted before its saved to their back end and it has no way to get the unedited version...   serious regex will be needed to fix this,.

**Comment by jimmycuadra** [comment]
Finally addressed by #35!
